modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved (See Github)"

issueTrackerURL="https://github.com/WolfShotz/Wyrmroost/issues"

[[mods]]

modId="wyrmroost"
version="${file.jarVersion}"
displayName="Wyrmroost"
# logoFile="examplemod.png"
#credits="Novacraft: Rooststalker Model and Textures"
authors="WolfShotz, Kingdomall, Shannieann, Ukan"
#description=''' '''

[[dependencies.wyrmroost]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wyrmroost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"